name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - 'tickets/**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd tickets && docker build -t shahabnamvar/tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - run: docker push shahabnamvar/tickets
